name: Run Tests

on: [pull_request, push, workflow_call, workflow_dispatch]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:17-3.5-alpine
        env:
          POSTGRES_PASSWORD: carg
          POSTGRES_DB: carg
          POSTGRES_USER: carg
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, curl, gd
      - name: Copy .env
        run: cp .env-example .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Add hosts to /etc/hosts
        run: sudo echo "127.0.0.1 db" | sudo tee -a /etc/hosts
      - name: Migrate
        run: php artisan migrate
        env:
          PGPASSWORD: carg
      - name: Clear the config cache
        run: php artisan config:clear
      - name: Optimize
        run: php artisan optimize
      - name: Laravel Tests
        run: php artisan test
